"""Optional, evidence-only semantic claim verification.

The verifier depends on a tiny ``create`` protocol rather than an SDK.  An
``OpenAI().responses`` adapter can therefore be supplied directly, while tests
and offline callers can use a deterministic fake.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping
from enum import Enum
from typing import Any, Literal, Protocol

from pydantic import Field, StrictFloat, StrictInt, StrictStr

from .models import StrictModel
from .schema import strict_json_schema
from .verification import (
    ClaimReference,
    EvidenceInput,
    EvidenceRecord,
    ReportLike,
    extract_claim_references,
)


class SemanticVerdict(str, Enum):
    """Allowed evidence-grounding judgments."""

    SUPPORTED = "supported"
    PARTIAL = "partial"
    UNSUPPORTED = "unsupported"
    CONTRADICTED = "contradicted"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


ConfidenceBasis = Literal["direct", "multi_source", "partial", "absence", "conflict"]
ErrorCode = Literal["model_error", "invalid_response", "invalid_citation_reference"]


class SemanticModelClient(Protocol):
    """Small adapter-friendly interface implemented by Responses clients."""

    def create(self, **request: Any) -> Any:
        """Return one structured model response."""


class SemanticJudgeOutput(StrictModel):
    """Strict object generated by the semantic judge."""

    verdict: SemanticVerdict
    confidence: StrictFloat = Field(ge=0.0, le=1.0)
    confidence_basis: ConfidenceBasis
    rationale: StrictStr = Field(min_length=1, max_length=1_000)
    supporting_citation_ids: list[StrictStr] = Field(default_factory=list, max_length=12)
    conflicting_citation_ids: list[StrictStr] = Field(default_factory=list, max_length=12)


class SemanticVerificationError(StrictModel):
    """Stable error information safe to expose in traces and evaluations."""

    code: ErrorCode
    message: StrictStr = Field(min_length=1, max_length=200)


class SemanticClaimCheck(StrictModel):
    """Semantic verification result for one report claim."""

    claim_id: StrictStr = Field(min_length=1, max_length=120)
    statement: StrictStr = Field(min_length=1, max_length=2_000)
    citation_ids: list[StrictStr] = Field(default_factory=list, max_length=12)
    evaluated_citation_ids: list[StrictStr] = Field(default_factory=list, max_length=12)
    verdict: SemanticVerdict
    confidence: StrictFloat = Field(ge=0.0, le=1.0)
    confidence_basis: ConfidenceBasis
    rationale: StrictStr = Field(min_length=1, max_length=1_000)
    supporting_citation_ids: list[StrictStr] = Field(default_factory=list, max_length=12)
    conflicting_citation_ids: list[StrictStr] = Field(default_factory=list, max_length=12)
    error: SemanticVerificationError | None = None
    method: Literal["evidence_only_semantic"] = "evidence_only_semantic"


class SemanticVerificationReport(StrictModel):
    """Aggregate semantic-verification output."""

    claim_checks: list[SemanticClaimCheck] = Field(default_factory=list, max_length=64)
    supported_claim_count: StrictInt = Field(ge=0)
    partial_claim_count: StrictInt = Field(ge=0)
    unsupported_claim_count: StrictInt = Field(ge=0)
    contradicted_claim_count: StrictInt = Field(ge=0)
    insufficient_evidence_claim_count: StrictInt = Field(ge=0)
    error_count: StrictInt = Field(ge=0)
    method: Literal["evidence_only_semantic"] = "evidence_only_semantic"


_SYSTEM_PROMPT = """You are an evidence-grounding verifier.
Judge whether the CLAIM is supported using ONLY the supplied EVIDENCE records.
Never use prior knowledge, browsing, assumptions, or facts absent from EVIDENCE.

Verdicts:
- supported: the evidence directly supports the full material claim.
- partial: the evidence supports only part of the claim or requires a caveat.
- unsupported: relevant evidence is present but does not support the claim.
- contradicted: the evidence directly conflicts with the claim.
- insufficient_evidence: the supplied evidence is missing, ambiguous, or too weak.

Confidence is confidence in the verdict, not confidence that the claim is true.
Reserve high confidence for explicit evidence; lower it for ambiguity or inference.
Reference only citation IDs present in EVIDENCE and return exactly the schema."""

_CONFIDENCE_CAPS: dict[ConfidenceBasis, float] = {
    "direct": 0.90,
    "multi_source": 1.0,
    "partial": 0.74,
    "absence": 0.65,
    "conflict": 0.95,
}

_STABLE_ERRORS: dict[ErrorCode, str] = {
    "model_error": "The semantic model call failed.",
    "invalid_response": "The semantic model returned an invalid structured response.",
    "invalid_citation_reference": "The semantic model referenced evidence outside the supplied set.",
}


def semantic_response_format() -> dict[str, Any]:
    """Return a strict Responses API ``text.format`` value."""

    return {
        "type": "json_schema",
        "name": "semantic_evidence_verdict",
        "strict": True,
        "schema": strict_json_schema(SemanticJudgeOutput),
    }


def _read(item: Any, key: str, default: Any = None) -> Any:
    if isinstance(item, Mapping):
        return item.get(key, default)
    return getattr(item, key, default)


def _normalize_record(item: Any, fallback_id: str | None) -> EvidenceRecord | None:
    citation_id = _read(item, "citation_id", _read(item, "id", _read(item, "source_id", fallback_id)))
    title = _read(item, "title", "Untitled source")
    evidence_text = _read(
        item,
        "evidence_text",
        _read(item, "evidence", _read(item, "text", _read(item, "snippet"))),
    )
    if not all(isinstance(value, str) and value.strip() for value in (citation_id, title, evidence_text)):
        return None
    try:
        return EvidenceRecord(
            citation_id=citation_id,
            title=title,
            text=evidence_text,
            source_url=_read(item, "source_url", _read(item, "url")),
            provider=_read(item, "provider"),
        )
    except (TypeError, ValueError):
        return None


def _normalize_evidence(evidence: EvidenceInput) -> dict[str, EvidenceRecord]:
    items: Iterable[tuple[str | None, Any]]
    if isinstance(evidence, Mapping):
        items = ((str(key), value) for key, value in evidence.items())
    else:
        items = ((None, value) for value in evidence)
    records: dict[str, EvidenceRecord] = {}
    for fallback_id, item in items:
        record = _normalize_record(item, fallback_id)
        if record is not None and record.citation_id not in records:
            records[record.citation_id] = record
    return records


def _parse_response(response: Any) -> SemanticJudgeOutput:
    """Parse common Responses adapter shapes without weakening strict mode."""

    if isinstance(response, SemanticJudgeOutput):
        return response
    if isinstance(response, (str, bytes, bytearray)):
        return SemanticJudgeOutput.model_validate_json(response)
    if isinstance(response, Mapping):
        if "output_text" in response:
            return _parse_response(response["output_text"])
        return SemanticJudgeOutput.model_validate_json(
            json.dumps(response, ensure_ascii=False)
        )
    output_text = getattr(response, "output_text", None)
    if isinstance(output_text, str):
        return SemanticJudgeOutput.model_validate_json(output_text)
    raise ValueError("No structured output was returned.")


def _failure(claim: ClaimReference, valid_ids: list[str], code: ErrorCode) -> SemanticClaimCheck:
    return SemanticClaimCheck(
        claim_id=claim.claim_id,
        statement=claim.statement,
        citation_ids=claim.citation_ids,
        evaluated_citation_ids=valid_ids,
        verdict=SemanticVerdict.INSUFFICIENT_EVIDENCE,
        confidence=0.0,
        confidence_basis="absence",
        rationale=_STABLE_ERRORS[code],
        error=SemanticVerificationError(code=code, message=_STABLE_ERRORS[code]),
    )


class SemanticEvidenceVerifier:
    """Verify report claims with an optional evidence-only semantic judge."""

    method = "evidence_only_semantic"

    def __init__(self, client: SemanticModelClient, *, model: str = "gpt-5-mini") -> None:
        self._client = client
        self._model = model

    def _verify_claim(
        self,
        claim: ClaimReference,
        evidence_by_id: Mapping[str, EvidenceRecord],
    ) -> SemanticClaimCheck:
        valid_ids = [citation_id for citation_id in claim.citation_ids if citation_id in evidence_by_id]
        if not valid_ids:
            return _failure(claim, valid_ids, "invalid_citation_reference")

        evidence_payload = [
            {
                "citation_id": citation_id,
                "title": evidence_by_id[citation_id].title,
                "text": evidence_by_id[citation_id].text,
            }
            for citation_id in valid_ids
        ]
        request = {
            "model": self._model,
            "input": [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": json.dumps(
                        {"claim": claim.statement, "evidence": evidence_payload},
                        ensure_ascii=False,
                        sort_keys=True,
                    ),
                },
            ],
            "text": {"format": semantic_response_format()},
        }
        try:
            raw_response = self._client.create(**request)
        except Exception:
            return _failure(claim, valid_ids, "model_error")
        try:
            judged = _parse_response(raw_response)
        except (TypeError, ValueError, json.JSONDecodeError):
            return _failure(claim, valid_ids, "invalid_response")

        referenced_ids = set(judged.supporting_citation_ids) | set(judged.conflicting_citation_ids)
        if not referenced_ids.issubset(valid_ids):
            return _failure(claim, valid_ids, "invalid_citation_reference")

        confidence = round(min(judged.confidence, _CONFIDENCE_CAPS[judged.confidence_basis]), 4)
        return SemanticClaimCheck(
            claim_id=claim.claim_id,
            statement=claim.statement,
            citation_ids=claim.citation_ids,
            evaluated_citation_ids=valid_ids,
            verdict=judged.verdict,
            confidence=confidence,
            confidence_basis=judged.confidence_basis,
            rationale=judged.rationale,
            supporting_citation_ids=judged.supporting_citation_ids,
            conflicting_citation_ids=judged.conflicting_citation_ids,
        )

    def verify(self, report: ReportLike, evidence: EvidenceInput) -> SemanticVerificationReport:
        """Verify every extracted claim, returning stable per-claim failures."""

        evidence_by_id = _normalize_evidence(evidence)
        checks = [
            self._verify_claim(claim, evidence_by_id)
            for claim in extract_claim_references(report)
        ]
        counts = {
            verdict: sum(check.verdict is verdict for check in checks)
            for verdict in SemanticVerdict
        }
        return SemanticVerificationReport(
            claim_checks=checks,
            supported_claim_count=counts[SemanticVerdict.SUPPORTED],
            partial_claim_count=counts[SemanticVerdict.PARTIAL],
            unsupported_claim_count=counts[SemanticVerdict.UNSUPPORTED],
            contradicted_claim_count=counts[SemanticVerdict.CONTRADICTED],
            insufficient_evidence_claim_count=counts[SemanticVerdict.INSUFFICIENT_EVIDENCE],
            error_count=sum(check.error is not None for check in checks),
        )


__all__ = [
    "SemanticClaimCheck",
    "SemanticEvidenceVerifier",
    "SemanticJudgeOutput",
    "SemanticModelClient",
    "SemanticVerdict",
    "SemanticVerificationError",
    "SemanticVerificationReport",
    "semantic_response_format",
]
